global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "nodejs" # Renamed to match standard dashboards
    static_configs:
      - targets: ["host.docker.internal:5000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
